### PR TITLE
fix: Add existing assets to albums

### LINKED ISSUE #45: [Feature]: Use the CLI to add assets already on the server to an Album
When adding multiple albums with some duplicate images it misses the files which are already on the server.  this also wont add them to the album.  a mechanism is needed to identify whats already on the server and also add it to the album

### PR DESCRIPTION
**Pull request by conneryn**
If an asset already exists on the server, it was being skipped entirely.  In the upload case, this makes sense, but when adding assets to albums, we may want to add the same asset to multiple albums.  So we shouldn't just ignore the asset altogether.

This PR updates the CLI to account for assets that already exist on the server if "createAlbum" is set, so all new and existing local assets are added to albums.

Fixes #45

### CODE REVIEW

**Comment by sohail579** [comment]
Hi @conneryn thanks for doing this, how do i use this now so that i can test if it works?

**Comment by conneryn** [comment]
@sohail579, thanks for taking a look. There are two main ways to test this I think:

**Upload an existing image to a specific album**

1. Upload an image (or images) without assigning it to any albums (`immich upload -d ./`)
2. Re-upload the same image (or images) but with an album set (`immich upload -d ./ --album TestAlbum`)
3. You should see the image(s) added to the album "TestAlbum"

**Upload multiple folders that contain identical images at the same time.**

1. Create two folders (`mkdir test && mkdir test/AlbumA && mkdir test/AlbumB`)
2. Copy the same image into both folders (`cp imageX.jpg ./test/AlbumA && cp imageX.jpg ./test/AlbumB`)
3. Upload both folders at once with the album flag set (`immich upload -d ./test --album`)
5. You should see the image(s) added to both "AlbumA" and "AlbumB".

Let me know if there is anything else I can help with.

**Comment by sohail579** [comment]
OK great I have all the files i need to test this as I have been having this issue a lot.

do i need to do anything to up date my CLI tool to include this fix?

**Comment by conneryn** [comment]
Once a contributor for `immich` accepts this PR, then there will likely be a new release that would make this available as a regular upgrade (`npm upgrade -g immich`).   In the meantime, if you are able to checkout the code, you can pull and run it manually to test:

1. Get the code: `git clone https://github.com/immich-app/CLI.git && cd CLI`
3. Install and build the code: `npm install && npm build`
4. Create a command alias: `alias immich-test="node $PWD/bin/index.js"`
5. Run commands: `immich-test --help`

Alternatively, I could publish a temporary build of this to npm under a different package name, if the above isn't doable for you.

**Comment by alextran1502** [comment]
Hello, thank you for the PR. I was doing a quick test and noticed some issues.

## First issue - Image uploaded from different method i.e Web upload doesn't get added to the album

1. Update `image-1.jpeg` by dragging and dropping it on the web
2. Drag `image-1.jpeg` and `image-2.jpeg` to a folder named `test-album`
3. Run the CLI command with the flag `--album` at the top-level folder where the `test-album` directory is located. 
4. CLI recognized two new assets to be backed up to the server.
5. Upon backing up, only one asset, `image-2.jpeg` get added to the album `test-album`

I should be expecting `image-1.jpeg` get added to the server as well, correct?

## Second issue - each time running the CLI command, all files will be uploaded again.

The second issue I observed was the command now will try to re-upload the already uploaded file again. 

This behavior is not intended for the CLI tools, as the tool will need to upload the newly added file only. 

I believe the issue is from removing the lines below

image

**Comment by conneryn** [comment]
**Re: First Issue**

Good catch, I had not tested this! The CLI only checks for "existing" assets based on the device ID (`axios.get(`${endpoint}/asset/${deviceId}`), and as I understand it, the Web and CLI uploads are considered different devices.   Luckily it appears the server is smart enough to detect the duplicates upon upload.  When a duplicate is uploaded it returns a status code 200 instead of 201. However, the CLI previously only considered a successful upload on a status 201, which meant it would skip the album assignments on a 200 response.  I have pushed a fix for this, by treating 200 and 201 the same.  

The only downside here is the CLI does still attempt the upload of the asset (waste of time and bandwidth), but I am not sure if there is a way to prevent this (the CLI would need to know about ALL assets in the account AND be able to perform the same de-duplication checks as the server, which would require more information that simply the `deviceAssetId`).

**Re: Second Issue**

The duplicate assets are not actually being uploaded a second time, but it does loop through each to determine if it should be uploaded (and only performs the upload: `if (!backupAsset.includes(asset.id)) {`).   However, I agree, the messaging displayed to the user needs improvement.

I've made a small change to improve this messaging, but I am very open to suggestions of what/how we should inform the user.

Message when uploading with `--album` flag set:
image

Message when uploading without the `--album` flag set:
image

**Comment by sohail579** [comment]
> 1. git clone https://github.com/immich-app/CLI.git && cd CLI

Thanks for the instructions, im still new to all this and learning so will give it a try.  also saw the comments from Alex.  I do have duplicates which have come from another device so should i not test this yet?

**Comment by alextran1502** [comment]
Hello, I rerun some tests after pulling the new update. Issue 1 has been resolved, as the items uploaded by another method are also added to the album.

However, issue 2 message is still a bit unclear to me.

image

The above screenshot shows every time I run the command with the flag `--album`. I believe the 1 asset that is indicated as the uploaded candidate is the asset I used the web method to upload. I believe that one asset will still be uploaded, correct?

Maybe we will need to incorporate some server changes as well to make this feature work out well.

**Comment by bo0tzz** [comment]
I think this is just the nature of the way we check whether to upload the files, and it would happen with the version of the CLI before this PR as well? I think the way to resolve it would be clientside hashing, which we've discussed before.

**Comment by sohail579** [comment]
> Once a contributor for `immich` accepts this PR, then there will likely be a new release that would make this available as a regular upgrade (`npm upgrade -g immich`). In the meantime, if you are able to checkout the code, you can pull and run it manually to test:
> 
> 1. Get the code: `git clone https://github.com/conneryn/immich-cli-takeout.git && cd immich-cli-takeout && git checkout feat/45-add-existing-asset-to-album`
> 2. Install and build the code: `npm install && npm run build`
> 3. Create a command alias: `alias immich-test="node $PWD/bin/index.js"`
> 4. Run commands: `immich-test --help`
> 
> Alternatively, I could publish a temporary build of this to npm under a different package name, if the above isn't doable for you.

Just to let you know I'm doing this on and some of the commands come wuup with errors maybe if you can publish this please?

**Comment by sohail579** [comment]
> However, as @bo0tzz mentions, this is the existing behaviour of the CLI, and is not directly related to this PR. So, I'd suggest we create a separate issue to look into addressing this (and I'd argue the issue is just a performance optimization, as the end result is "correct", it just may have taken a little extra time/bandwidth to get there).

Thanks @conneryn appreciate the efforts

**Comment by bo0tzz** [comment]
@alextran1502 can we merge this, or does it still need changes?

**Comment by sohail579** [comment]
has this been added to the latest release now?

**Comment by sohail579** [comment]
> @alextran1502, you are right, assets previously uploaded from a different device will not be recognized as already uploaded by the CLI. This is because the CLI only checks for existing assets based on the current `deviceId`. In order to be able to actually detect cross-device assets, I think we would need:
> 
> 1. a new server endpoint that exposes the hashes for all assets in the users account, and
> 2. the client(s) to have the knowledge/ability to also produce these hashes themselves
> 
> However, as @bo0tzz mentions, this is the existing behaviour of the CLI, and is not directly related to this PR. So, I'd suggest we create a separate issue to look into addressing this (and I'd argue the issue is just a performance optimization, as the end result is "correct", it just may have taken a little extra time/bandwidth to get there).
> 
> @sohail579, sorry you ran into errors with the commands. I think we may be close to getting this merged, so just hang tight another day or two I think.

any news on this?

**Comment by alextran1502** [comment]
Forgot about this, will run a few more test and merge it in

**Comment by sohail579** [comment]
> Forgot about this, will run a few more test and merge it in

Excellent thanks

**Pull request merged**
