### PR TITLE
chore: remove client-side exif parsing

### PR DESCRIPTION
**Pull request by etnoy**
Immich recently migrated to the following library for date and time extraction: https://github.com/photostructure/exiftool-vendored.js#dates

The reason for the migration is that many photos have underspecified timezones. exiftool-vendored takes care of this nicely.

Users like myself with lots of DSLR photos not taken by mobile phones run into this issue all the time.

This pull request makes the date and time extraction consistent with immich itself.

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
I actually don't think we should have any exif parsing in the cli.

This is duplicate code to what is already happening on the server. Can we instead remove exif parsing, and use `asset.fileCreatedAt`?

**Comment by bo0tzz** [comment]
I agree with @jrasm91. I think anything done here would be overridden when the server runs its exif extraction anyways.

**Comment by jrasm91** [comment]
The only thing this impacts (which we could solve another way) is that the asset _could temporarily_ show up in the wrong place in the timeline. This would only impact assets loaded into the web/client AFTER the thumbnail has been generated, but BEFORE exif extraction completes, which is where the correct date gets set.

**Comment by etnoy** [comment]
I also would like to remove the date. The only edge case I can think of is when a photo has zero exif data and the last modified time of the filesystem is the only thing to go by. Also I don't like putting to much trust in client-provided parameters from a security perspective.

However, removing the date field from the upload requires an API change as it is a required parameter when uploading.

For the sake of this PR, let's merge as-is and then propose the API change separately.

**Comment by jrasm91** [comment]
There are two separate issues here. (1) the API interface, which requires a date and (2) the date the immich ultimately will use.

I agree we can defer (1), but (2) will ALWAYS be set, even in the case of no exif data. It will still try to extract it and it will still fallback to file modified date. 

I think we should still remove all the exif stuff. Since we're going to avoid (1) in this PR you can pass literally any date you want in the file created at, since it is essentially ignored/replaced server-side for ALL files.

**Comment by jrasm91** [comment]
Actually looks like it could fallback to the originally provided timestamps if there is no exif.

https://github.com/immich-app/immich/blob/main/server/apps/microservices/src/processors/metadata-extraction.processor.ts#L170-L171

In that case, we should definitely be passing the timestamps from the filesystem.

**Comment by etnoy** [comment]
In that case let's remove the whole exif parsing mess from the cli and just pass the mtime instead

**Review by jrasm91 — APPROVED** [review]
LGTM

**Pull request merged**
